name: Development Android Build

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    name: Build Dev APK
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Dummy Test
        run: |
          echo "Running a dummy test for 1 second..."
          sleep 1
          echo "Test passed!"

      - name: Create .env.dev file
        run: |
          mkdir -p env
          echo 'BASE_URL=${{ secrets.DEV_BASE_URL }}' >> env/.env.dev
          echo 'SOME_API_KEY=${{ secrets.DEV_SOME_API_KEY }}' >> env/.env.dev
          echo 'GOOGLE_MAPS_API_KEY=${{ secrets.DEV_GOOGLE_MAPS_API_KEY }}' >> env/.env.dev

      - name: Build APK
        run: flutter build apk --release --dart-define-from-file=env/.env.dev

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: development-apk
          path: build/app/outputs/flutter-apk/app-release.apk
